services:
  backend:
    build: ./server
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME:-team_flow}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"

  frontend:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - backend
