spring.application.name=server
server.port=8080
spring.datasource.url=jdbc:mysql://${DB_HOST:8.137.146.104}:${DB_PORT:3306}/${DB_NAME:team_flow}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:jade}
spring.datasource.password=${DB_PASSWORD:20041114Liuyu!}

spring.sql.init.schema-locations=classpath:schema-mysql.sql
spring.sql.init.mode=never


