spring.application.name=server
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/team_flow?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:root}
